env:
    global:
        - PACKAGE="PluginTester"

matrix:
    include:
        - os: linux
          language: python
          env: SUBLIME_TEXT_VERSION="2"
        - os: linux
          language: python
          env: SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests --coverage